#################################
#####       语言文件        #####
#################################
language: "language_cn.yml"
#################################
#####         权限          #####
#################################
#重新读取配置文件的权限
per_lib_reloadConfig: "per.lib.reloadConfig"
#################################
#####         配置          #####
#################################
#玩家发出命令最小间隔
cmdInterval: 500